// <auto-generated />
namespace Shop.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class merge1104 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(merge1104));
        
        string IMigrationMetadata.Id
        {
            get { return "201704111202179_merge 11.04"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
